# Generated by Django 3.1.7 on 2021-03-27 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('client', models.CharField(max_length=250)),
                ('location', models.CharField(max_length=250)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('IN_PROGRESS_DELAYED', 'In Progress - Delayed'), ('IN_PROGRESS_ON_TRACK', 'In Progress - On Track'), ('TERMINATED', 'Terminated'), ('COMPLETED', 'Completed')], default='NS', max_length=30)),
                ('progress_indicator', models.IntegerField()),
                ('image', models.ImageField(default='images/ewc.jpg', upload_to='')),
                ('value', models.FloatField()),
                ('user', models.ManyToManyField(related_name='_project_user_+', to='main_app.Project')),
            ],
        ),
    ]
