# Generated by Django 3.1.7 on 2021-04-16 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20210406_1818'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(default='images/build5.jpg', upload_to='gallery_photos/%Y/%m/')),
                ('description', models.CharField(max_length=300)),
                ('place', models.CharField(max_length=250)),
                ('date_created', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
